#!/usr/bin/python3

# Reads the HH Audio Services table and outputs a json representation of the entries
# desired to be in the LDAP directory

# Importing the required modules 
import sys
import json
import mysql.connector
from common import *

properties = readProperties()
db = connectDB(properties['dbHost'], properties['dbUser'], properties['dbPassword'], properties['dbSchema'])

baseDN='ou=phonebook,dc=hamshackhotline,dc=com'

result={}

# first add the container for these entries
result[baseDN]={
    'objectClass': ['top','organizationalUnit'],
    'ou': ['phonebook'],
    'description': ['container for entries']
}

baseDN='ou=audio,ou=phonebook,dc=hamshackhotline,dc=com'
result[baseDN]={
    'objectClass': ['top','organizationalUnit'],
    'ou': ['audio'],
    'description': ['container for entries']
}

if db:
    cursor = db.cursor()
    cursor.execute('select Id,Name,Number,Notes,Status from audioServices;')
    # 0 ID
    # 1 Name
    # 2 Number
    # 3 Notes
    # 4 Status
    for row in cursor.fetchall():
        name=row[1].strip()
        number=str(row[2]).strip()

        id="a-"+number
        dn="hamshackhotlineComEntryID=" + id + ","+baseDN

        result[dn]={
            'objectClass': ['top','hamshackhotlineComEntry'],
            'cn': [name], 
            'givenName': [name],
            'name': [name],
            'telephoneNumber': [number], 
            'displayName': [name],
            'hamshackhotlineComEntryID': [id]
        }

json.dump(result,sys.stdout)
