#!/usr/bin/python3

# Reads the HH Audio Bridges HTML page from stdin and outputs a json representation of the entries
# desired to be in the LDAP directory

# Importing the required modules 
import sys
import json
import mysql.connector

propertiesFilename = 'hhAgent.properties'
prop = {}
def readProperties():
    global prop
    with open(propertiesFilename, 'r') as f:
        for line in f:
            line = line.rstrip() #removes trailing whitespace and '\n' chars

            if "=" not in line: continue #skips blanks and comments w/o =
            if line.startswith("#"): continue #skips comments which contain =

            k, v = line.split("=", 1)
            prop[k] = v

def connectDB(host,user,passwd,schema):
    try:
        config = {
            "host": host,
            "user": user,
            "password": passwd,
            "database": schema,
        }
        db = mysql.connector.connect(**config)
        cursor = db.cursor()
        cursor.execute("SELECT VERSION()")
        results = cursor.fetchone()
        # Check if anything at all is returned
        if results:
            return db
        else:
            return None
    except mysql.connector.errors.ProgrammingError as ex:
        print("ERROR IN CONNECTION")
        print(ex)
        return None

readProperties()
db = connectDB(prop['dbHost'], prop['dbUser'], prop['dbPassword'], prop['dbSchema'])

baseDN='ou=phonebook,dc=hamshackhotline,dc=com'

result={}

# first add the container for these entries
result[baseDN]={
    'objectClass': ['top','organizationalUnit'],
    'ou': ['phonebook'],
    'description': ['container for entries']
}

baseDN='ou=audio,ou=phonebook,dc=hamshackhotline,dc=com'
result[baseDN]={
    'objectClass': ['top','organizationalUnit'],
    'ou': ['audio'],
    'description': ['container for entries']
}

if db:
    cursor = db.cursor()
    cursor.execute('select Id,Name,Number,Notes,Status from audioServices;')
    # 0 ID
    # 1 Name
    # 2 Number
    # 3 Notes
    # 4 Status
    for row in cursor.fetchall():
        name=row[1].strip()
        number=str(row[2]).strip()

        id="a-"+number
        dn="hamshackhotlineComEntryID=" + id + ","+baseDN

        result[dn]={
            'objectClass': ['top','hamshackhotlineComEntry'],
            'cn': [name], 
            'givenName': [name],
            'name': [name],
            'telephoneNumber': [number], 
            'displayName': [name],
            'hamshackhotlineComEntryID': [id]
        }

json.dump(result,sys.stdout)
