#!/usr/bin/python3
# Importing the required modules 
import sys
import json

result={}
targetFiles = sys.argv[1:]

for filename in targetFiles:
    with open(filename,'r') as f:
        result.update(json.load(f))

json.dump(result,sys.stdout)