#!/usr/bin/python3
# Importing the required modules 
import sys
import json

result={}
targetFiles = ['data/targetVanity.json','data/targetAudioBridges.json','data/targetRFLinks.json','data/targetBridges.json','data/targetPhones.json']

for filename in targetFiles:
    with open(filename,'r') as f:
        result.update(json.load(f))

json.dump(result,sys.stdout)