#!/usr/bin/python3

# Reads the HH Directory HTML page from stdin and outputs a json representation of the entries
# desired to be in the LDAP directory

# Importing the required modules 
import sys
from bs4 import BeautifulSoup
import json

baseDN='ou=phonebook,dc=hamshackhotline,dc=com'

result={}

# first add the container for these entries
result[baseDN]={
    'objectClass': ['top','organizationalUnit'],
    'ou': ['phonebook'],
    'description': ['container for entries']
}

baseDN='ou=phones,ou=phonebook,dc=hamshackhotline,dc=com'
result[baseDN]={
    'objectClass': ['top','organizationalUnit'],
    'ou': ['phones'],
    'description': ['container for entries']
}


soup = BeautifulSoup(sys.stdin.buffer,'html.parser')

# for getting the data 
HTML_data = soup.find_all("table")[2].find("tbody").find_all("tr")

for element in HTML_data:
    sub_data = []
    for sub_element in element.find_all("td"):
        try:
            sub_data.append(sub_element.get_text())
        except:
            continue
 
    # 0 Callsign
    # 1 Name
    # 2 City
    # 3 State
    # 4 Country
    # 5 Network
    # 6 HH Number
    # 7 Ring Group
 
    callsign=sub_data[0].strip()
    name=sub_data[1].strip()
    city=sub_data[2].strip()
    state=sub_data[3].strip()
    country=sub_data[4].strip()
    tel=sub_data[6].strip()
    idPrefix=tel

    id=idPrefix
    dn="hamshackhotlineComEntryID=" + id + ","+baseDN

    count=0
    while (dn in result):
        count+=1
        id=idPrefix + "-" + str(count)
        dn="hamshackhotlineComEntryID=" + id + ","+baseDN

    result[dn]={
        'objectClass': ['top','hamshackhotlineComEntry'],
        'cn': [name,callsign], 
        'givenName': [name],
        'name': [name],
        'callsign': [callsign],
        'telephoneNumber': [tel], 
        'displayName': [callsign+" "+name],
        'hamshackhotlineComEntryID': [id]
    }
    if (city):
        result[dn]['l'] = [city]
    if (state):
        result[dn]['st'] = [state]
    if (country and (len(country) == 2)):
        result[dn]['c'] = [country]


json.dump(result,sys.stdout)
