#!/usr/bin/python3

# Reads the HH Arduino table and outputs a json representation of the entries
# desired to be in the LDAP directory

# Importing the required modules 
import sys
import json
import mysql.connector
from common import *

properties = readProperties()
db = connectDB(properties['dbHost'], properties['dbUser'], properties['dbPassword'], properties['dbSchema'])

baseDN='ou=phonebook,dc=hamshackhotline,dc=com'

result={}

# first add the container for these entries
result[baseDN]={
    'objectClass': ['top','organizationalUnit'],
    'ou': ['phonebook'],
    'description': ['container for entries']
}

baseDN='ou=arduino,ou=phonebook,dc=hamshackhotline,dc=com'
result[baseDN]={
    'objectClass': ['top','organizationalUnit'],
    'ou': ['arduino'],
    'description': ['container for entries']
}


if db:
    cursor = db.cursor()
    cursor.execute('select Id,Number,Channel,Description,City,State,Country,Frequency,plTone,Mode from hhArduino;')
    # 0 ID
    # 1 Number
    # 2 Channel
    # 3 Description
    # 4 City
    # 5 State
    # 6 Country
    # 7 Frequency
    # 8 plTone
    # 9 Mode

    for row in cursor.fetchall():
        number=str(row[1]).strip()
        channel=row[2].strip()
        description=row[3].strip()
        city=row[4].strip()
        state=row[5].strip()
        country=row[6].strip()
        frequency=row[7].strip()
        plTone=row[8].strip()
        mode=row[9].strip()

        callsign=description.split()[0].strip()
        id="al-"+number
        dn="hamshackhotlineComEntryID=" + id + ","+baseDN

        result[dn]={
            'objectClass': ['top','hamshackhotlineComEntry'],
            'cn': [description], 
            'givenName': [description],
            'name': [description],
            'callsign': [callsign],
            'telephoneNumber': [number], 
            'displayName': [description],
            'hamshackhotlineComEntryID': [id]
        }

json.dump(result,sys.stdout)
