#!/usr/bin/python3

# Reads the HH Audio Bridges table and outputs a json representation of the entries
# desired to be in the LDAP directory

# Importing the required modules 
import sys
import json
import mysql.connector
from common import *

properties = readProperties()
db = connectDB(properties['dbHost'], properties['dbUser'], properties['dbPassword'], properties['dbSchema'])

baseDN='ou=phonebook,dc=hamshackhotline,dc=com'

result={}

# first add the container for these entries
result[baseDN]={
    'objectClass': ['top','organizationalUnit'],
    'ou': ['phonebook'],
    'description': ['container for entries']
}

baseDN='ou=bridges,ou=phonebook,dc=hamshackhotline,dc=com'
result[baseDN]={
    'objectClass': ['top','organizationalUnit'],
    'ou': ['bridges'],
    'description': ['container for entries']
}


if db:
    cursor = db.cursor()
    cursor.execute('select Id,cName,isPublic,Network,Number,Mname,Mnumber from hhBridge;')
    # 0 ID
    # 1 cName
    # 2 isPublic
    # 3 Network
    # 4 Number
    # 5 Mname
    # 6 Mnumber
    for row in cursor.fetchall():
        name=row[1].strip().upper()
        isPublic=row[2].strip()
        network=row[3].strip()
        number=str(row[4]).strip()
        mName=row[5].strip()
        mNumber=str(row[6]).strip()

        if (isPublic == "Y"):
            displayName=name
        else:
            displayName="[Private] "+name
        id="b-"+number
        dn="hamshackhotlineComEntryID=" + id + ","+baseDN

        result[dn]={
            'objectClass': ['top','hamshackhotlineComEntry'],
            'cn': [name], 
            'givenName': [name],
            'name': [name],
            'telephoneNumber': [number], 
            'displayName': [displayName],
            'hamshackhotlineComEntryID': [id]
        }

json.dump(result,sys.stdout)
