#!/usr/bin/python3

# Reads an LDIF file from stdin and outputs a json representation of the entries 
# only includes entries matching the baseDN and the desired attributes

# Importing the required modules 
import sys
import ldif
import json

# Will move parameters later
baseDN='ou=phonebook,dc=hamshackhotline,dc=com'
importantAttributes = ['objectClass','sn','cn','telephoneNumber','description','callsign',
                       'givenName','name','displayName','hamshackhotlineComEntryID', 'ou',
                       'l','st','c']

# Initialize result array
result = {}

parser = ldif.LDIFParser(sys.stdin.buffer)
parser.parse()

for dn, entry in parser.parse():
    if (dn.endswith(baseDN)):
        result[dn] = {}
        for attr in importantAttributes:
            if (attr in entry.keys()):
                result[dn][attr] = entry[attr]

json.dump(result,sys.stdout)
